/**
 * VeilPass contract tests — run with: npm test
 *
 * Tests run directly against the compiled contract JavaScript generated by the
 * Compact compiler, using the @midnight-ntwrk/compact-runtime simulation API.
 *
 * Key architecture details:
 *   1. contract.initialState(constructorContext) executes the constructor,
 *      which initializes policy_threshold = 18 on the public ledger.
 *   2. contract.circuits.checkEligibility(ctx, threshold) returns CircuitResults.
 *      The updated ledger state is in CircuitResults.context.currentQueryContext.state.state
 *      (a StateValue), NOT in the input ctx (which holds an immutable copy).
 *   3. VeilPass.ledger(ChargedState) decodes field values from a ChargedState.
 */
import * as path from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';
import {
  dummyContractAddress,
  createCircuitContext,
  createConstructorContext,
  ChargedState,
  ContractState,
} from '@midnight-ntwrk/compact-runtime';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const contractPath = path.resolve(
  __dirname, '..', 'contracts', 'managed', 'veilpass', 'contract', 'index.js',
);

// ─── Load compiled contract ──────────────────────────────────────────────────

const VeilPass = await import(pathToFileURL(contractPath).href);

// ─── Helpers ─────────────────────────────────────────────────────────────────

const DUMMY_COIN_PK = { bytes: new Uint8Array(32).fill(0) };

/**
 * Build a contract instance with the given private age wired into the witness,
 * and return the initial contract state from constructor execution.
 */
function setup(ageForWitness: bigint): {
  contract: InstanceType<typeof VeilPass.Contract>;
  initialContractState: ContractState;
} {
  const contract = new VeilPass.Contract({
    privateAge: (_ctx: any): [{}, bigint] => [{}, ageForWitness],
  });
  const constructorContext = createConstructorContext({}, DUMMY_COIN_PK);
  const result = contract.initialState(constructorContext);
  return { contract, initialContractState: result.currentContractState };
}

/**
 * Run the checkEligibility circuit.
 * Returns the new ChargedState and raw circuit results.
 * Throws if any circuit assertion fails (ineligible, policy violation, etc.).
 */
function runCircuit(
  contract: InstanceType<typeof VeilPass.Contract>,
  contractState: ContractState,
  threshold: bigint,
) {
  const ctx = createCircuitContext(
    dummyContractAddress(),
    DUMMY_COIN_PK,
    contractState.data,
    {},
  );
  const circuitResult = contract.circuits.checkEligibility(ctx, threshold);
  const chargedState = new ChargedState(circuitResult.context.currentQueryContext.state.state);
  return { chargedState, circuitResult };
}

// ─── Test runner ─────────────────────────────────────────────────────────────

let passed = 0;
let failed = 0;

function test(name: string, fn: () => void): void {
  try {
    fn();
    console.log(`  ✅ PASS: ${name}`);
    passed++;
  } catch (err: any) {
    console.log(`  ❌ FAIL: ${name}`);
    console.log(`         ${err?.message ?? err}`);
    failed++;
  }
}

function assert(condition: boolean, message: string): void {
  if (!condition) throw new Error(message);
}

// ─── Tests ───────────────────────────────────────────────────────────────────

console.log('\n╔══════════════════════════════════════════════════════════════╗');
console.log('║                VeilPass — Contract Tests                     ║');
console.log('╚══════════════════════════════════════════════════════════════╝\n');

// TEST 1: Initial Ledger State from Constructor
test('Initialization: constructor sets policy_threshold=18, eligible=false, threshold_used=0', () => {
  const { initialContractState } = setup(25n);
  const ls = VeilPass.ledger(initialContractState.data);
  assert(ls.policy_threshold === 18n, `expected policy_threshold=18, got ${ls.policy_threshold}`);
  assert(ls.eligible === false, `expected eligible=false initially, got ${ls.eligible}`);
  assert(ls.threshold_used === 0n, `expected threshold_used=0 initially, got ${ls.threshold_used}`);
});

// TEST 2: Eligible input meeting threshold
test('Eligible: age 25 >= threshold 18 → eligible=true, threshold_used=18, policy_threshold=18', () => {
  const { contract, initialContractState } = setup(25n);
  const { chargedState } = runCircuit(contract, initialContractState, 18n);
  const ls = VeilPass.ledger(chargedState);
  assert(ls.eligible === true, `expected eligible=true, got ${ls.eligible}`);
  assert(ls.threshold_used === 18n, `expected threshold_used=18, got ${ls.threshold_used}`);
  assert(ls.policy_threshold === 18n, `expected policy_threshold=18, got ${ls.policy_threshold}`);
});

// TEST 3: Ineligible input — age below threshold
test('Ineligible: age 16 < threshold 18 → circuit assertion throws', () => {
  const { contract, initialContractState } = setup(16n);
  let threw = false;
  let errorMsg = '';
  try {
    runCircuit(contract, initialContractState, 18n);
  } catch (err: any) {
    threw = true;
    errorMsg = err?.message ?? String(err);
  }
  assert(threw, 'expected circuit to throw for ineligible age, but it succeeded');
  assert(
    errorMsg.includes('age is below threshold'),
    `expected "age is below threshold" failure, got: ${errorMsg}`,
  );
});

// TEST 4: Policy Enforcement — caller CANNOT lower threshold to zero
test('Policy Security: caller passing threshold=0 is rejected (cannot lower requirement to 0)', () => {
  const { contract, initialContractState } = setup(25n);
  let threw = false;
  let errorMsg = '';
  try {
    runCircuit(contract, initialContractState, 0n);
  } catch (err: any) {
    threw = true;
    errorMsg = err?.message ?? String(err);
  }
  assert(threw, 'expected circuit to reject threshold=0, but it was accepted');
  assert(
    errorMsg.includes('threshold cannot be below policy threshold'),
    `expected policy error, got: ${errorMsg}`,
  );
});

// TEST 5: Policy Enforcement — caller CANNOT bypass policy with threshold=17 even if age=17
test('Policy Security: minor (age 17) cannot bypass age gate by requesting threshold=17', () => {
  // Minor caller attempts to set threshold to their own age (17) to force eligibility
  const { contract, initialContractState } = setup(17n);
  let threw = false;
  let errorMsg = '';
  try {
    runCircuit(contract, initialContractState, 17n);
  } catch (err: any) {
    threw = true;
    errorMsg = err?.message ?? String(err);
  }
  assert(threw, 'expected circuit to reject threshold=17, but it was accepted');
  assert(
    errorMsg.includes('threshold cannot be below policy threshold'),
    `expected policy violation error, got: ${errorMsg}`,
  );
});

// TEST 6: Boundary — age exactly equals policy threshold (18 == 18)
test('Boundary: age === threshold === policy_threshold (all 18) → eligible=true', () => {
  const { contract, initialContractState } = setup(18n);
  const { chargedState } = runCircuit(contract, initialContractState, 18n);
  const ls = VeilPass.ledger(chargedState);
  assert(ls.eligible === true, `expected eligible=true at boundary, got ${ls.eligible}`);
  assert(ls.threshold_used === 18n, `expected threshold_used=18, got ${ls.threshold_used}`);
});

// TEST 7: Higher valid threshold (e.g. 21 for restricted goods)
test('Configurable Threshold: age 22 >= threshold 21 >= policy 18 → eligible=true, threshold_used=21', () => {
  const { contract, initialContractState } = setup(22n);
  const { chargedState } = runCircuit(contract, initialContractState, 21n);
  const ls = VeilPass.ledger(chargedState);
  assert(ls.eligible === true, `expected eligible=true, got ${ls.eligible}`);
  assert(ls.threshold_used === 21n, `expected threshold_used=21, got ${ls.threshold_used}`);
  assert(ls.policy_threshold === 18n, `expected policy_threshold=18, got ${ls.policy_threshold}`);
});

// TEST 8: Privacy Inspection on Public Ledger and Circuit Outputs
test('Privacy Inspection: private witness value (42) does not appear in ledger state or circuit return', () => {
  const privateAge = 42n;
  const threshold = 18n;
  const { contract, initialContractState } = setup(privateAge);
  const { chargedState, circuitResult } = runCircuit(contract, initialContractState, threshold);
  const ls = VeilPass.ledger(chargedState);

  // 1. Inspect on-chain public ledger fields
  assert(ls.eligible === true, 'expected eligible=true');
  assert(ls.threshold_used === threshold, `expected threshold_used=${threshold}, got ${ls.threshold_used}`);
  assert(ls.policy_threshold === 18n, `expected policy_threshold=18, got ${ls.policy_threshold}`);

  // Confirm none of the public ledger values equal the private input (42)
  assert(
    ls.threshold_used !== privateAge,
    `Leak: threshold_used equals private age ${privateAge}`,
  );
  assert(
    ls.policy_threshold !== privateAge,
    `Leak: policy_threshold equals private age ${privateAge}`,
  );

  // 2. Inspect circuit return value
  // In Compact, checkEligibility returns [] (empty tuple). Verify no data returned.
  assert(
    Array.isArray(circuitResult.result) && circuitResult.result.length === 0,
    `Circuit result leaked data: ${JSON.stringify(circuitResult.result)}`,
  );
});

// ─── Summary ─────────────────────────────────────────────────────────────────

console.log(`\n  Results: ${passed} passed, ${failed} failed\n`);
if (failed > 0) process.exit(1);
